version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sep6-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1icdhqimjan7b"
s3_prefix = "sep6-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
